name: Test Gollo

on: 
  push

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq nasm
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.6
      - name: Run tests
        run: |
          make test